import circle from "../assets/circle.svg";

const images = {
  email: require("../assets/email.png"),
  mobile: require("../assets/mobile.png"),
  api: require("../assets/api.png"),
  cpp: require("../assets/cpp.png"),
  css: require("../assets/css.png"),
  figma: require("../assets/figma.png"),
  flutter: require("../assets/flutter.png"),
  git: require("../assets/git.png"),
  graphql: require("../assets/graphql.png"),
  html: require("../assets/html.png"),
  javascript: require("../assets/javascript.png"),
  mu5: require("../assets/mu5.png"),
  node: require("../assets/node.png"),
  python: require("../assets/python.png"),
  react: require("../assets/react.png"),
  redux: require("../assets/redux.png"),
  sass: require("../assets/sass.png"),
  typescript: require("../assets/typescript.png"),
  vue: require("../assets/vue.png"),
  about01: require("../assets/about01.png"),
  about02: require("../assets/about02.png"),
  about03: require("../assets/about03.png"),
  about04: require("../assets/about04.png"),
  profile: require("../assets/alwin123.png"),
  circle,
  logo: require("../assets/asvg.png"),
  adidas: require("../assets/adidas.png"),
  amazon: require("../assets/amazon.png"),
  asus: require("../assets/asus.png"),
  bolt: require("../assets/bolt.png"),
  nb: require("../assets/nb.png"),
  skype: require("../assets/skype.png"),
  spotify: require("../assets/spotify.png"),
};

export default images;
